name: Update Submodule in Private Repo

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dotfiles repo
        uses: actions/checkout@v4
        with:
          repository: pgijsbertsen/dotfiles
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true

      - name: Update & commit submodules to dotfiles repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git submodule update --remote --merge
          git add --all
          git commit -m "Update nvim to latest commit" || echo "No changes to commit"
          git push
